### ISSUE TITLE
Password Reset Link Not Working

### ISSUE THREAD

**Issue by Flicker17** [Codesly/BrilliantRetail#2]
If a user on our site enters their email address to reset their password an email with a reset password link is generated, and sent to the user. This link, however, is not sending them to a page where they can reset their password. It sends them to a profile page that lists Recent Orders. Any attempt to click Profile, or Edit returns them to the login page/form. Below are the main parts being used in the templates to generate the password reset link:

RESET/RETRIEVE PASSWORD PAGE
{exp:brilliant_retail:forgot_password id="password_form"}
Retrieve Your Password
  Please enter your e-mail below to retrieve your password.
  `<label>`Email
`<input class=“txtinp required email” name=“email” type=“text” /></label>`
  `<div class=“loginBtn”>`
      `<div class=“ibtnWpr”>`
        `<div class=“ibtn”>`
          Submit
          `<input name=”” type=“image” src=”{theme}/images/0.gif” alt=“Submit” />`
        `</div>`
      `</div>`
  `</div>`
`</form>`
{/exp:brilliant_retail:forgot_password}
RESET PASSWORD EMAIL
Password Reset Link: {link}
 
EXAMPLE OF THE LINK THAT IS GENERATE
http://www.companyname.com/customer/password_reset/random-set-of-numbers-letters
 
Again, this link brings the user to a profile page that lists recent orders, not to their profile to reset their password. Anyone have any insight as to what may be going on, and a fix?

**Comment by dpdexter** [comment]
The password_reset template exists in your design customer.group correct?

**Comment by Flicker17** [comment]
Correct, however, after looking at it again the file is name "password.html" would this have any effect on that?

**Comment by dpdexter** [comment]
password.html and password_reset.html are separate templates. 

Please review the source files here:

https://github.com/Codesly/BrilliantRetail/tree/master/themes/site_themes/brilliant_retail/customer.group

**Comment by Flicker17** [comment]
Terrific, that fixed the problem. The theme we took over was missing that file. Thank you!
